### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by marenz2569** [FiendChain/ViterbiDecoderCpp#1]
Hi, under which license is this code distributable?

LICENSE file says MIT, but there are references in the code to LGPL
https://github.com/FiendChain/ViterbiDecoderCpp/blob/17514d16867796b1cdc5635137824659c2568ce0/include/viterbi/viterbi_decoder_core.h#L4

**Comment by williamyang98** [comment]
Thanks for indicating this problem to me. I've updated the license so that it should conform to the LGPL terms.
